In [4]:
from scipy import signal
import numpy as np

In [5]:
w0 = 2*np.pi*5

In [12]:
print(w0)

31.41592653589793


In [18]:
num=w0;
den=[1, w0];
H=signal.TransferFunction(num,den)
print(H)

TransferFunctionContinuous(
array([31.41592654]),
array([ 1.        , 31.41592654]),
dt: None
)


In [20]:
T=1.0/1000.0;
print (T)

0.001


In [24]:
Hd=H.to_discrete(T,method='gbt',alpha=0.5)
print(Hd)

TransferFunctionDiscrete(
array([0.01546504, 0.01546504]),
array([ 1.        , -0.96906992]),
dt: 0.001
)


In [28]:
b = Hd.num;
a = Hd.den;
print("Coeficientes b_i: " + str(b))
print("Coeficientes a_i: " + str(a[1:]))

Coeficientes b_i: [0.01546504 0.01546504]
Coeficientes a_i: [-0.96906992]
